# Generated by Django 3.2 on 2023-12-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolioapp32', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='abstract',
            field=models.TextField(max_length=255),
        ),
    ]
